# App config example.

# PostgreSQL storage configuration
# Connection URL
DATABASE_URL:
  "postgres://user:password@localhost:5432/project?sslmode=disable"

# Log level
LOG_LEVEL:
  "info"

# Request timeout
TIMEOUT:
  "5s"

# Server address
SERVER_ADDRESS:
  "127.0.0.1:8080"

# Sectet key
SECRET_KEY:
  "secret_key"
